name: Continuous Deployment


on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: [completed]
    branches: [main, dev]     

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy API
        run: |
          curl -X POST "https://api.render.com/deploy/${{ secrets.RENDER_API_SERVICE_ID }}" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      - name: Deploy Web
        run: |
          curl -X POST "https://api.render.com/deploy/${{ secrets.RENDER_WEB_SERVICE_ID }}" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"